import 'package:flutter/cupertino.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HorseRecordsModel {
  int? id;
  String? type;
  String? bestTs;
  String? or;
  String? netTotalPrize;
  String? wins;
  String? starts;
  String? createdAt;
  String? updatedAt;
  String? horseUid;

  HorseRecordsModel({
    this.id,
    this.type,
    this.bestTs,
    this.or,
    this.netTotalPrize,
    this.wins,
    this.starts,
    this.createdAt,
    this.updatedAt,
    this.horseUid,
  });
  HorseRecordsModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    type = json["type"]?.toString();
    bestTs = json["best_ts"]?.toString();
    or = json["or"]?.toString();
    netTotalPrize = json["net_total_prize"]?.toString();
    wins = json["wins"]?.toString();
    starts = json["starts"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    horseUid = json["horse_uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["type"] = type;
    data["best_ts"] = bestTs;
    data["or"] = or;
    data["net_total_prize"] = netTotalPrize;
    data["wins"] = wins;
    data["starts"] = starts;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["horse_uid"] = horseUid;
    return data;
  }
}

class HorseRecordProvider extends ChangeNotifier {
  HorseRecordsModel? recordsModel;
  HorseRecordsModel? rulesRace;
  HorseRecordsModel? flatTurf;
  HorseRecordsModel? allWeather;
  HorseRecordsModel? stakes;

  addHorserecods(List<dynamic> data) {
    //recordsModel = data;
    if (data.isNotEmpty) {
      allWeather = HorseRecordsModel.fromJson(data[0]);
      rulesRace = HorseRecordsModel.fromJson(data[1]);
      flatTurf = HorseRecordsModel.fromJson(data[2]);
      stakes = HorseRecordsModel.fromJson(data[3]);
    }
    notifyListeners();
  }

  clearProvider() {
    recordsModel = null;
    rulesRace = null;
    flatTurf = null;
    allWeather = null;
    stakes = null;
    notifyListeners();
  }
}
