import 'package:flutter/cupertino.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HorseProfileModelDataProfileToFollow {
/*
{
  "to_follow_uid": 54,
  "to_follow_desc": "Rabbah 21",
  "to_follow_code": "}",
  "hit_flag": false
} 
*/

  int? toFollowUid;
  String? toFollowDesc;
  String? toFollowCode;
  bool? hitFlag;

  HorseProfileModelDataProfileToFollow({
    this.toFollowUid,
    this.toFollowDesc,
    this.toFollowCode,
    this.hitFlag,
  });
  HorseProfileModelDataProfileToFollow.fromJson(Map<String, dynamic> json) {
    toFollowUid = json["to_follow_uid"]?.toInt();
    toFollowDesc = json["to_follow_desc"]?.toString();
    toFollowCode = json["to_follow_code"]?.toString();
    hitFlag = json["hit_flag"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["to_follow_uid"] = toFollowUid;
    data["to_follow_desc"] = toFollowDesc;
    data["to_follow_code"] = toFollowCode;
    data["hit_flag"] = hitFlag;
    return data;
  }
}

class HorseProfileModelDataProfileTrainerLast_14Days {
/*
{
  "runs": 45,
  "wins": 13,
  "percent": 29
} 
*/

  int? runs;
  int? wins;
  int? percent;

  HorseProfileModelDataProfileTrainerLast_14Days({
    this.runs,
    this.wins,
    this.percent,
  });
  HorseProfileModelDataProfileTrainerLast_14Days.fromJson(
      Map<String, dynamic> json) {
    runs = json["runs"]?.toInt();
    wins = json["wins"]?.toInt();
    percent = json["percent"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["runs"] = runs;
    data["wins"] = wins;
    data["percent"] = percent;
    return data;
  }
}

class HorseProfileModelDataProfileTips {
/*
{
  "race_instance_uid": 788192,
  "newspaper_uid": 12,
  "naps_style": "Robin Goodfellow"
} 
*/

  int? raceInstanceUid;
  int? newspaperUid;
  String? napsStyle;

  HorseProfileModelDataProfileTips({
    this.raceInstanceUid,
    this.newspaperUid,
    this.napsStyle,
  });
  HorseProfileModelDataProfileTips.fromJson(Map<String, dynamic> json) {
    raceInstanceUid = json["race_instance_uid"]?.toInt();
    newspaperUid = json["newspaper_uid"]?.toInt();
    napsStyle = json["naps_style"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["race_instance_uid"] = raceInstanceUid;
    data["newspaper_uid"] = newspaperUid;
    data["naps_style"] = napsStyle;
    return data;
  }
}

class HorseProfileModelDataProfile {
  int? horseUid;
  String? horseName;
  String? horseCountryOriginCode;
  String? horseDateOfBirth;
  String? horseDateOfDeath;
  String? age;
  String? dateGelded;
  int? sireUid;
  int? damUid;
  String? sireHorseName;
  String? sireCountryOriginCode;
  String? damHorseName;
  String? damCountryOriginCode;
  String? damSireHorseName;
  String? damSireCountryOriginCode;
  int? siresSireUid;
  String? siresSireName;
  String? ownerName;
  int? ownerUid;
  String? ownerPtpTypeCode;
  String? trainerName;
  int? trainerUid;
  String? trainerLocation;
  String? trainerPtpTypeCode;
  String? breederName;
  String? horseColourCode;
  String? horseSexCode;
  String? silkImagePath;
  List<HorseProfileModelDataProfileTips?>? tips;
  String? comments;
  HorseProfileModelDataProfileTrainerLast_14Days? trainerLast_14Days;
  String? previousTrainers;
  String? previousOwners;
  int? damSireUid;
  bool? damStatus;
  bool? sireStatus;
  String? horseSex;
  String? horseColour;
  String? sireComment;
  String? avgFlatWinDist;
  double? sireAvgFlatWinDist;
  double? damSireAvgFlatWinDist;
  String? avgWinDistance;
  double? sireAvgWinDistance;
  double? damSireAvgWinDistance;
  String? avgEarningsIndex;
  String? studFee;
  String? weatherbysUid;
  List<HorseProfileModelDataProfileToFollow?>? toFollow;
  int? ownerGroupUid;

  HorseProfileModelDataProfile({
    this.horseUid,
    this.horseName,
    this.horseCountryOriginCode,
    this.horseDateOfBirth,
    this.horseDateOfDeath,
    this.age,
    this.dateGelded,
    this.sireUid,
    this.damUid,
    this.sireHorseName,
    this.sireCountryOriginCode,
    this.damHorseName,
    this.damCountryOriginCode,
    this.damSireHorseName,
    this.damSireCountryOriginCode,
    this.siresSireUid,
    this.siresSireName,
    this.ownerName,
    this.ownerUid,
    this.ownerPtpTypeCode,
    this.trainerName,
    this.trainerUid,
    this.trainerLocation,
    this.trainerPtpTypeCode,
    this.breederName,
    this.horseColourCode,
    this.horseSexCode,
    this.silkImagePath,
    this.tips,
    this.comments,
    this.trainerLast_14Days,
    this.previousTrainers,
    this.previousOwners,
    this.damSireUid,
    this.damStatus,
    this.sireStatus,
    this.horseSex,
    this.horseColour,
    this.sireComment,
    this.avgFlatWinDist,
    this.sireAvgFlatWinDist,
    this.damSireAvgFlatWinDist,
    this.avgWinDistance,
    this.sireAvgWinDistance,
    this.damSireAvgWinDistance,
    this.avgEarningsIndex,
    this.studFee,
    this.weatherbysUid,
    this.toFollow,
    this.ownerGroupUid,
  });
  HorseProfileModelDataProfile.fromJson(Map<String, dynamic> json) {
    horseUid = json["horse_uid"]?.toInt();
    horseName = json["horse_name"]?.toString();
    horseCountryOriginCode = json["horse_country_origin_code"]?.toString();
    horseDateOfBirth = json["horse_date_of_birth"]?.toString();
    horseDateOfDeath = json["horse_date_of_death"]?.toString();
    age = json["age"]?.toString();
    dateGelded = json["date_gelded"]?.toString();
    sireUid = json["sire_uid"]?.toInt();
    damUid = json["dam_uid"]?.toInt();
    sireHorseName = json["sire_horse_name"]?.toString();
    sireCountryOriginCode = json["sire_country_origin_code"]?.toString();
    damHorseName = json["dam_horse_name"]?.toString();
    damCountryOriginCode = json["dam_country_origin_code"]?.toString();
    damSireHorseName = json["dam_sire_horse_name"]?.toString();
    damSireCountryOriginCode = json["dam_sire_country_origin_code"]?.toString();
    siresSireUid = json["sires_sire_uid"]?.toInt();
    siresSireName = json["sires_sire_name"]?.toString();
    ownerName = json["owner_name"]?.toString();
    ownerUid = json["owner_uid"]?.toInt();
    ownerPtpTypeCode = json["owner_ptp_type_code"]?.toString();
    trainerName = json["trainer_name"]?.toString();
    trainerUid = json["trainer_uid"]?.toInt();
    trainerLocation = json["trainer_location"]?.toString();
    trainerPtpTypeCode = json["trainer_ptp_type_code"]?.toString();
    breederName = json["breeder_name"]?.toString();
    horseColourCode = json["horse_colour_code"]?.toString();
    horseSexCode = json["horse_sex_code"]?.toString();
    silkImagePath = json["silk_image_path"]?.toString();
    if (json["tips"] != null) {
      final v = json["tips"];
      final arr0 = <HorseProfileModelDataProfileTips>[];
      v.forEach((v) {
        arr0.add(HorseProfileModelDataProfileTips.fromJson(v));
      });
      tips = arr0;
    }
    comments = json["comments"]?.toString();
    trainerLast_14Days = (json["trainer_last_14_days"] != null)
        ? HorseProfileModelDataProfileTrainerLast_14Days.fromJson(
            json["trainer_last_14_days"])
        : null;
    previousTrainers = json["previous_trainers"]?.toString();
    previousOwners = json["previous_owners"]?.toString();
    damSireUid = json["dam_sire_uid"]?.toInt();
    damStatus = json["dam_status"];
    sireStatus = json["sire_status"];
    horseSex = json["horse_sex"]?.toString();
    horseColour = json["horse_colour"]?.toString();
    sireComment = json["sire_comment"]?.toString();
    avgFlatWinDist = json["avg_flat_win_dist"]?.toString();
    sireAvgFlatWinDist = json["sire_avg_flat_win_dist"]?.toDouble();
    damSireAvgFlatWinDist = json["dam_sire_avg_flat_win_dist"]?.toDouble();
    avgWinDistance = json["avg_win_distance"]?.toString();
    sireAvgWinDistance = json["sire_avg_win_distance"]?.toDouble();
    damSireAvgWinDistance = json["dam_sire_avg_win_distance"]?.toDouble();
    avgEarningsIndex = json["avg_earnings_index"]?.toString();
    studFee = json["stud_fee"]?.toString();
    weatherbysUid = json["weatherbys_uid"]?.toString();
    if (json["to_follow"] != null) {
      final v = json["to_follow"];
      final arr0 = <HorseProfileModelDataProfileToFollow>[];
      v.forEach((v) {
        arr0.add(HorseProfileModelDataProfileToFollow.fromJson(v));
      });
      toFollow = arr0;
    }
    ownerGroupUid = json["owner_group_uid"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["horse_uid"] = horseUid;
    data["horse_name"] = horseName;
    data["horse_country_origin_code"] = horseCountryOriginCode;
    data["horse_date_of_birth"] = horseDateOfBirth;
    data["horse_date_of_death"] = horseDateOfDeath;
    data["age"] = age;
    data["date_gelded"] = dateGelded;
    data["sire_uid"] = sireUid;
    data["dam_uid"] = damUid;
    data["sire_horse_name"] = sireHorseName;
    data["sire_country_origin_code"] = sireCountryOriginCode;
    data["dam_horse_name"] = damHorseName;
    data["dam_country_origin_code"] = damCountryOriginCode;
    data["dam_sire_horse_name"] = damSireHorseName;
    data["dam_sire_country_origin_code"] = damSireCountryOriginCode;
    data["sires_sire_uid"] = siresSireUid;
    data["sires_sire_name"] = siresSireName;
    data["owner_name"] = ownerName;
    data["owner_uid"] = ownerUid;
    data["owner_ptp_type_code"] = ownerPtpTypeCode;
    data["trainer_name"] = trainerName;
    data["trainer_uid"] = trainerUid;
    data["trainer_location"] = trainerLocation;
    data["trainer_ptp_type_code"] = trainerPtpTypeCode;
    data["breeder_name"] = breederName;
    data["horse_colour_code"] = horseColourCode;
    data["horse_sex_code"] = horseSexCode;
    data["silk_image_path"] = silkImagePath;
    if (tips != null) {
      final v = tips;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["tips"] = arr0;
    }
    data["comments"] = comments;
    if (trainerLast_14Days != null) {
      data["trainer_last_14_days"] = trainerLast_14Days!.toJson();
    }
    data["previous_trainers"] = previousTrainers;
    data["previous_owners"] = previousOwners;
    data["dam_sire_uid"] = damSireUid;
    data["dam_status"] = damStatus;
    data["sire_status"] = sireStatus;
    data["horse_sex"] = horseSex;
    data["horse_colour"] = horseColour;
    data["sire_comment"] = sireComment;
    data["avg_flat_win_dist"] = avgFlatWinDist;
    data["sire_avg_flat_win_dist"] = sireAvgFlatWinDist;
    data["dam_sire_avg_flat_win_dist"] = damSireAvgFlatWinDist;
    data["avg_win_distance"] = avgWinDistance;
    data["sire_avg_win_distance"] = sireAvgWinDistance;
    data["dam_sire_avg_win_distance"] = damSireAvgWinDistance;
    data["avg_earnings_index"] = avgEarningsIndex;
    data["stud_fee"] = studFee;
    data["weatherbys_uid"] = weatherbysUid;
    if (toFollow != null) {
      final v = toFollow;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["to_follow"] = arr0;
    }
    data["owner_group_uid"] = ownerGroupUid;
    return data;
  }
}

class HorseProfileModelData {
  HorseProfileModelDataProfile? profile;
  String? entries;
  String? quotes;
  String? stableTourQuotes;

  HorseProfileModelData({
    this.profile,
    this.entries,
    this.quotes,
    this.stableTourQuotes,
  });
  HorseProfileModelData.fromJson(Map<String, dynamic> json) {
    profile = (json["profile"] != null)
        ? HorseProfileModelDataProfile.fromJson(json["profile"])
        : null;
    entries = json["entries"]?.toString();
    quotes = json["quotes"]?.toString();
    stableTourQuotes = json["stable_tour_quotes"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (profile != null) {
      data["profile"] = profile!.toJson();
    }
    data["entries"] = entries;
    data["quotes"] = quotes;
    data["stable_tour_quotes"] = stableTourQuotes;
    return data;
  }
}

class HorseProfileModel {
  HorseProfileModelData? data;
  int? status;

  HorseProfileModel({
    this.data,
    this.status,
  });
  HorseProfileModel.fromJson(Map<String, dynamic> json) {
    data = (json["data"] != null)
        ? HorseProfileModelData.fromJson(json["data"])
        : null;
    status = json["status"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["data"] = this.data!.toJson();
    data["status"] = status;
    return data;
  }
}

class HorseProfileProvider extends ChangeNotifier {
  HorseProfileModel? profile;
  addProfile(HorseProfileModel data) {
    profile = data;
    notifyListeners();
  }
}
