import 'package:flutter/cupertino.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HorseFormModel {
  int? id;
  int? ownerUid;
  String? raceInstanceUid;
  String? courseRpAbbrev_3;
  String? raceOutcomeCode;
  String? oddsDesc;
  String? raceDatetime;
  String? createdAt;
  String? updatedAt;
  String? distanceFurlong;
  String? noOfRunners;
  String? officialRatingRanOff;
  String? horseUid;

  HorseFormModel({
    this.id,
    this.ownerUid,
    this.raceInstanceUid,
    this.courseRpAbbrev_3,
    this.raceOutcomeCode,
    this.oddsDesc,
    this.raceDatetime,
    this.createdAt,
    this.updatedAt,
    this.distanceFurlong,
    this.noOfRunners,
    this.officialRatingRanOff,
    this.horseUid,
  });
  HorseFormModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    ownerUid = json["owner_uid"]?.toInt();
    raceInstanceUid = json["race_instance_uid"]?.toString();
    courseRpAbbrev_3 = json["course_rp_abbrev_3"]?.toString();
    raceOutcomeCode = json["race_outcome_code"]?.toString();
    oddsDesc = json["odds_desc"]?.toString();
    raceDatetime = json["race_datetime"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    distanceFurlong = json["distance_furlong"]?.toString();
    noOfRunners = json["no_of_runners"]?.toString();
    officialRatingRanOff = json["official_rating_ran_off"]?.toString();
    horseUid = json["horse_uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["owner_uid"] = ownerUid;
    data["race_instance_uid"] = raceInstanceUid;
    data["course_rp_abbrev_3"] = courseRpAbbrev_3;
    data["race_outcome_code"] = raceOutcomeCode;
    data["odds_desc"] = oddsDesc;
    data["race_datetime"] = raceDatetime;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["distance_furlong"] = distanceFurlong;
    data["no_of_runners"] = noOfRunners;
    data["official_rating_ran_off"] = officialRatingRanOff;
    data["horse_uid"] = horseUid;
    return data;
  }
}

class HorseFormProvider extends ChangeNotifier {
  List<HorseFormModel> formModel = [];
  addFormData(List<HorseFormModel> data) {
    print(data);
    //  formModel.addAll(data);
    for (var i in data) {
      formModel.add(i);
    }
    notifyListeners();
  }

  clearProvider() {
    formModel.clear();
    notifyListeners();
  }
}
