import 'package:flutter/cupertino.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HorseSalesModel {
/*
{
  "id": 678,
  "venue_desc": "TATTERSALLS",
  "abbrev_name": "Tattersalls Dec (foals)",
  "lot_no": "385",
  "price": "",
  "cur_code": "GNS",
  "seller_name": "From Bearstone Stud",
  "created_at": "2021-10-13 15:44:03",
  "updated_at": "2021-10-13 15:44:03",
  "buyer_detail": "Peter & Ross Doyle Bloodstock",
  "horse_uid": "2280385"
}
*/

  int? id;
  String? venueDesc;
  String? abbrevName;
  String? lotNo;
  String? price;
  String? curCode;
  String? sellerName;
  String? createdAt;
  String? updatedAt;
  String? buyerDetail;
  String? horseUid;

  HorseSalesModel({
    this.id,
    this.venueDesc,
    this.abbrevName,
    this.lotNo,
    this.price,
    this.curCode,
    this.sellerName,
    this.createdAt,
    this.updatedAt,
    this.buyerDetail,
    this.horseUid,
  });
  HorseSalesModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    venueDesc = json["venue_desc"]?.toString();
    abbrevName = json["abbrev_name"]?.toString();
    lotNo = json["lot_no"]?.toString();
    price = json["price"]?.toString();
    curCode = json["cur_code"]?.toString();
    sellerName = json["seller_name"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    buyerDetail = json["buyer_detail"]?.toString();
    horseUid = json["horse_uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["venue_desc"] = venueDesc;
    data["abbrev_name"] = abbrevName;
    data["lot_no"] = lotNo;
    data["price"] = price;
    data["cur_code"] = curCode;
    data["seller_name"] = sellerName;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["buyer_detail"] = buyerDetail;
    data["horse_uid"] = horseUid;
    return data;
  }
}

class HorseSalesProvider extends ChangeNotifier {
  List<HorseSalesModel> salesModel = [];
  addSalesModel(List<HorseSalesModel> data) {
    salesModel.addAll(data);
    notifyListeners();
  }

  clearProvider() {
    salesModel.clear();
    notifyListeners();
  }
}
