import 'package:flutter/material.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HorseEntriesModel {
/*
{
  "id": 66,
  "race_instance_title": "racingwelfa",
  "horse_uid": "3789372",
  "course_style_name": "Chelmsford (AW)",
  "race_datetime": "2021-10-14 18:30:00",
  "created_at": "2021-10-13 16:01:39",
  "updated_at": "2021-10-13 16:01:39",
  "race_instance_uid": "793769"
}
*/

  int? id;
  String? raceInstanceTitle;
  String? horseUid;
  String? courseStyleName;
  String? raceDatetime;
  String? createdAt;
  String? updatedAt;
  String? raceInstanceUid;

  HorseEntriesModel({
    this.id,
    this.raceInstanceTitle,
    this.horseUid,
    this.courseStyleName,
    this.raceDatetime,
    this.createdAt,
    this.updatedAt,
    this.raceInstanceUid,
  });
  HorseEntriesModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    raceInstanceTitle = json["race_instance_title"]?.toString();
    horseUid = json["horse_uid"]?.toString();
    courseStyleName = json["course_style_name"]?.toString();
    raceDatetime = json["race_datetime"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    raceInstanceUid = json["race_instance_uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["race_instance_title"] = raceInstanceTitle;
    data["horse_uid"] = horseUid;
    data["course_style_name"] = courseStyleName;
    data["race_datetime"] = raceDatetime;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["race_instance_uid"] = raceInstanceUid;
    return data;
  }
}

class HorseEntriesProvider extends ChangeNotifier {
  List<HorseEntriesModel> dataModel = [];
  addDataModel(List<HorseEntriesModel> data) {
    for (var i in data) {
      dataModel.add(i);
    }
    notifyListeners();
  }

  clearProvider() {
    dataModel.clear();
    notifyListeners();
  }
}
