import 'package:flutter/cupertino.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RaceDetailsModel {
/*
{
  "id": 1,
  "race_instance_uid": "790015",
  "horse_uid": "3294865",
  "horse_name": "Maraakiz",
  "race_datetime": "2021-08-26T17:00:00+01:00",
  "course_name": "CARLISLE",
  "course_style_name": "Carlisle",
  "race_status_code": "O",
  "ownerId": 302438,
  "race_instance_title": "Join Racing TV Now Handicap (JC Grassroots Middle Distance Series Qualifier)",
  "created_at": "2021-08-26 14:38:07",
  "updated_at": "2021-08-26 14:38:07",
  "ownerName": "SHADWELL ESTATE COMPANY LTD"
}
*/

  int? id;
  String? raceInstanceUid;
  String? horseUid;
  String? horseName;
  String? raceDatetime;
  String? courseName;
  String? courseStyleName;
  String? raceStatusCode;
  int? ownerId;
  String? raceInstanceTitle;
  String? createdAt;
  String? updatedAt;
  String? ownerName;

  RaceDetailsModel({
    this.id,
    this.raceInstanceUid,
    this.horseUid,
    this.horseName,
    this.raceDatetime,
    this.courseName,
    this.courseStyleName,
    this.raceStatusCode,
    this.ownerId,
    this.raceInstanceTitle,
    this.createdAt,
    this.updatedAt,
    this.ownerName,
  });
  RaceDetailsModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    raceInstanceUid = json["race_instance_uid"]?.toString();
    horseUid = json["horse_uid"]?.toString();
    horseName = json["horse_name"]?.toString();
    raceDatetime = json["race_datetime"]?.toString();
    courseName = json["course_name"]?.toString();
    courseStyleName = json["course_style_name"]?.toString();
    raceStatusCode = json["race_status_code"]?.toString();
    ownerId = json["ownerId"]?.toInt();
    raceInstanceTitle = json["race_instance_title"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    ownerName = json["ownerName"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["race_instance_uid"] = raceInstanceUid;
    data["horse_uid"] = horseUid;
    data["horse_name"] = horseName;
    data["race_datetime"] = raceDatetime;
    data["course_name"] = courseName;
    data["course_style_name"] = courseStyleName;
    data["race_status_code"] = raceStatusCode;
    data["ownerId"] = ownerId;
    data["race_instance_title"] = raceInstanceTitle;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["ownerName"] = ownerName;
    return data;
  }
}

class AvailableRaceProvider extends ChangeNotifier {
  List<RaceDetailsModel> availRaces = [];
  addRace(RaceDetailsModel data) {
    availRaces.add(data);
    notifyListeners();
  }
}

class UpcomingRaceProvider extends ChangeNotifier {
  List<RaceDetailsModel> comingRaces = [];
  addRace(RaceDetailsModel data) {
    comingRaces.add(data);
    notifyListeners();
  }
}

class CompletedRaceProvider extends ChangeNotifier {
  List<RaceDetailsModel> completeRaces = [];
  addRace(RaceDetailsModel data) {
    completeRaces.add(data);
    notifyListeners();
  }

  addList(List<RaceDetailsModel> list) {
    completeRaces = list;
    notifyListeners();
  }
}
