import 'package:flutter/cupertino.dart';
import 'package:racing_eye/Models/raceRunnersModel.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RaceResultsModelDataRaceCardPrizes {
/*
{
  "position_no": 1,
  "prize_sterling": 5454,
  "prize_euro": null,
  "prize_usd": 7471.98
} 
*/

  int? positionNo;
  int? prizeSterling;
  String? prizeEuro;
  double? prizeUsd;

  RaceResultsModelDataRaceCardPrizes({
    this.positionNo,
    this.prizeSterling,
    this.prizeEuro,
    this.prizeUsd,
  });
  RaceResultsModelDataRaceCardPrizes.fromJson(Map<String, dynamic> json) {
    positionNo = json["position_no"]?.toInt();
    prizeSterling = json["prize_sterling"]?.toInt();
    prizeEuro = json["prize_euro"]?.toString();
    prizeUsd = json["prize_usd"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["position_no"] = positionNo;
    data["prize_sterling"] = prizeSterling;
    data["prize_euro"] = prizeEuro;
    data["prize_usd"] = prizeUsd;
    return data;
  }
}

class RaceResultsModelDataRaceCard {
/*
{
  "race_instance_title": "Hoof It For PRD British EBF Restricted Novice Stakes (For Horses In Bands A, B, C And D) (GBB Race)",
  "race_number": 1,
  "rp_ages_allowed_desc": "2yo",
  "race_class": "4",
  "race_group_code": null,
  "official_rating_band_desc": null,
  "race_datetime": "2021-09-03T13:20:00+01:00",
  "local_meeting_race_datetime": "2021-09-03T13:20:00+01:00",
  "three_yo_min_weight_lbs": null,
  "four_yo_min_weight_lbs": null,
  "minimum_weight_lbs": null,
  "declared_runners": 8,
  "no_of_runners": 8,
  "distance_yard": 1320,
  "distance_furlong_rounded": 6,
  "rp_tv_text": "SKY",
  "going_type_desc": "Good",
  "rp_penalties": "each race won 6lb (Sellers and Claimers excluded for the purposes of penalties)",
  "course_uid": 2,
  "mixed_course_uid": null,
  "course_name": "ASCOT",
  "course_style_name": "Ascot",
  "course_region": "GB & IRE",
  "diffusion_course_name": "ASCOT",
  "course_key": "ascot",
  "small_map_image_path": "//images.racingpost.com/course_maps/small/ascot.jpg",
  "large_map_image_path": "//images.racingpost.com/course_maps/large/ascot.jpg",
  "rp_horse_types": "2yo, which are EBF eligible, which are in Bands A, B, C, and D",
  "rp_weights": "colts & geldings 9st 5lb; fillies 9st",
  "allowances": "Band B from Band A 2lb; Band C from Band B 2lb; Band D from Band C 2lb (allowances are cumulative)",
  "entry_fee": 40,
  "extra_fee": null,
  "country_code": "GB",
  "foreign": 0,
  "rp_stakes": 10100,
  "rp_ag_indicator": "G",
  "weights_raised_lbs": null,
  "rp_auction_min": null,
  "rp_claim_min": null,
  "rp_confirmed": null,
  "race_status_code": "R",
  "race_type_code": "F",
  "race_group_desc": null,
  "going_type_code": "G",
  "no_of_fences": null,
  "no_of_entries": 20,
  "rp_stalls_position": "H",
  "stalls_position_desc": "Stands' side",
  "prizes": [
    {
      "position_no": 1,
      "prize_sterling": 5454,
      "prize_euro": null,
      "prize_usd": 7471.98
    }
  ],
  "other_declarations": null,
  "claiming_prices": null,
  "forfeits": null,
  "forfeit_number": null,
  "forfeit_value": null,
  "stage": null,
  "highest_official_rating": null,
  "scoop6_race": false,
  "lucky7_race": false,
  "jackpot_race": false,
  "william_hill_offer_race": false,
  "ladbrokes_offer_race": false,
  "safety_factor_number": 20,
  "early_closing_race": false,
  "reopened": false,
  "division_preference": 1,
  "last_year": "2020 (10 ran) Dark Shift (5) Charles Hills 2 9-2 10/1 Kieran Shoemark RPR94",
  "perform_race_uid_atr": 846046,
  "perform_race_uid_ruk": null,
  "bet_to_view": false,
  "livestream_uid": null,
  "aw_surface_type": null,
  "straight_round_jubilee_code": null,
  "live_tab": false,
  "claiming_race": false,
  "selling_race": false,
  "plus10_race": false,
  "weight_for_age": null
} 
*/

  String? raceInstanceTitle;
  int? raceNumber;
  String? rpAgesAllowedDesc;
  String? raceClass;
  String? raceGroupCode;
  String? officialRatingBandDesc;
  String? raceDatetime;
  String? localMeetingRaceDatetime;
  String? threeYoMinWeightLbs;
  String? fourYoMinWeightLbs;
  String? minimumWeightLbs;
  int? declaredRunners;
  int? noOfRunners;
  int? distanceYard;
  int? distanceFurlongRounded;
  String? rpTvText;
  String? goingTypeDesc;
  String? rpPenalties;
  int? courseUid;
  String? mixedCourseUid;
  String? courseName;
  String? courseStyleName;
  String? courseRegion;
  String? diffusionCourseName;
  String? courseKey;
  String? smallMapImagePath;
  String? largeMapImagePath;
  String? rpHorseTypes;
  String? rpWeights;
  String? allowances;
  int? entryFee;
  String? extraFee;
  String? countryCode;
  int? foreign;
  int? rpStakes;
  String? rpAgIndicator;
  String? weightsRaisedLbs;
  String? rpAuctionMin;
  String? rpClaimMin;
  String? rpConfirmed;
  String? raceStatusCode;
  String? raceTypeCode;
  String? raceGroupDesc;
  String? goingTypeCode;
  String? noOfFences;
  int? noOfEntries;
  String? rpStallsPosition;
  String? stallsPositionDesc;
  List<RaceResultsModelDataRaceCardPrizes?>? prizes;
  String? otherDeclarations;
  String? claimingPrices;
  String? forfeits;
  String? forfeitNumber;
  String? forfeitValue;
  String? stage;
  String? highestOfficialRating;
  bool? scoop6Race;
  bool? lucky7Race;
  bool? jackpotRace;
  bool? williamHillOfferRace;
  bool? ladbrokesOfferRace;
  int? safetyFactorNumber;
  bool? earlyClosingRace;
  bool? reopened;
  int? divisionPreference;
  String? lastYear;
  int? performRaceUidAtr;
  String? performRaceUidRuk;
  bool? betToView;
  String? livestreamUid;
  String? awSurfaceType;
  String? straightRoundJubileeCode;
  bool? liveTab;
  bool? claimingRace;
  bool? sellingRace;
  bool? plus10Race;
  String? weightForAge;

  RaceResultsModelDataRaceCard({
    this.raceInstanceTitle,
    this.raceNumber,
    this.rpAgesAllowedDesc,
    this.raceClass,
    this.raceGroupCode,
    this.officialRatingBandDesc,
    this.raceDatetime,
    this.localMeetingRaceDatetime,
    this.threeYoMinWeightLbs,
    this.fourYoMinWeightLbs,
    this.minimumWeightLbs,
    this.declaredRunners,
    this.noOfRunners,
    this.distanceYard,
    this.distanceFurlongRounded,
    this.rpTvText,
    this.goingTypeDesc,
    this.rpPenalties,
    this.courseUid,
    this.mixedCourseUid,
    this.courseName,
    this.courseStyleName,
    this.courseRegion,
    this.diffusionCourseName,
    this.courseKey,
    this.smallMapImagePath,
    this.largeMapImagePath,
    this.rpHorseTypes,
    this.rpWeights,
    this.allowances,
    this.entryFee,
    this.extraFee,
    this.countryCode,
    this.foreign,
    this.rpStakes,
    this.rpAgIndicator,
    this.weightsRaisedLbs,
    this.rpAuctionMin,
    this.rpClaimMin,
    this.rpConfirmed,
    this.raceStatusCode,
    this.raceTypeCode,
    this.raceGroupDesc,
    this.goingTypeCode,
    this.noOfFences,
    this.noOfEntries,
    this.rpStallsPosition,
    this.stallsPositionDesc,
    this.prizes,
    this.otherDeclarations,
    this.claimingPrices,
    this.forfeits,
    this.forfeitNumber,
    this.forfeitValue,
    this.stage,
    this.highestOfficialRating,
    this.scoop6Race,
    this.lucky7Race,
    this.jackpotRace,
    this.williamHillOfferRace,
    this.ladbrokesOfferRace,
    this.safetyFactorNumber,
    this.earlyClosingRace,
    this.reopened,
    this.divisionPreference,
    this.lastYear,
    this.performRaceUidAtr,
    this.performRaceUidRuk,
    this.betToView,
    this.livestreamUid,
    this.awSurfaceType,
    this.straightRoundJubileeCode,
    this.liveTab,
    this.claimingRace,
    this.sellingRace,
    this.plus10Race,
    this.weightForAge,
  });
  RaceResultsModelDataRaceCard.fromJson(Map<String, dynamic> json) {
    raceInstanceTitle = json["race_instance_title"]?.toString();
    raceNumber = json["race_number"]?.toInt();
    rpAgesAllowedDesc = json["rp_ages_allowed_desc"]?.toString();
    raceClass = json["race_class"]?.toString();
    raceGroupCode = json["race_group_code"]?.toString();
    officialRatingBandDesc = json["official_rating_band_desc"]?.toString();
    raceDatetime = json["race_datetime"]?.toString();
    localMeetingRaceDatetime = json["local_meeting_race_datetime"]?.toString();
    threeYoMinWeightLbs = json["three_yo_min_weight_lbs"]?.toString();
    fourYoMinWeightLbs = json["four_yo_min_weight_lbs"]?.toString();
    minimumWeightLbs = json["minimum_weight_lbs"]?.toString();
    declaredRunners = json["declared_runners"]?.toInt();
    noOfRunners = json["no_of_runners"]?.toInt();
    distanceYard = json["distance_yard"]?.toInt();
    distanceFurlongRounded = json["distance_furlong_rounded"]?.toInt();
    rpTvText = json["rp_tv_text"]?.toString();
    goingTypeDesc = json["going_type_desc"]?.toString();
    rpPenalties = json["rp_penalties"]?.toString();
    courseUid = json["course_uid"]?.toInt();
    mixedCourseUid = json["mixed_course_uid"]?.toString();
    courseName = json["course_name"]?.toString();
    courseStyleName = json["course_style_name"]?.toString();
    courseRegion = json["course_region"]?.toString();
    diffusionCourseName = json["diffusion_course_name"]?.toString();
    courseKey = json["course_key"]?.toString();
    smallMapImagePath = json["small_map_image_path"]?.toString();
    largeMapImagePath = json["large_map_image_path"]?.toString();
    rpHorseTypes = json["rp_horse_types"]?.toString();
    rpWeights = json["rp_weights"]?.toString();
    allowances = json["allowances"]?.toString();
    entryFee = json["entry_fee"]?.toInt();
    extraFee = json["extra_fee"]?.toString();
    countryCode = json["country_code"]?.toString();
    foreign = json["foreign"]?.toInt();
    rpStakes = json["rp_stakes"]?.toInt();
    rpAgIndicator = json["rp_ag_indicator"]?.toString();
    weightsRaisedLbs = json["weights_raised_lbs"]?.toString();
    rpAuctionMin = json["rp_auction_min"]?.toString();
    rpClaimMin = json["rp_claim_min"]?.toString();
    rpConfirmed = json["rp_confirmed"]?.toString();
    raceStatusCode = json["race_status_code"]?.toString();
    raceTypeCode = json["race_type_code"]?.toString();
    raceGroupDesc = json["race_group_desc"]?.toString();
    goingTypeCode = json["going_type_code"]?.toString();
    noOfFences = json["no_of_fences"]?.toString();
    noOfEntries = json["no_of_entries"]?.toInt();
    rpStallsPosition = json["rp_stalls_position"]?.toString();
    stallsPositionDesc = json["stalls_position_desc"]?.toString();
    if (json["prizes"] != null) {
      final v = json["prizes"];
      final arr0 = <RaceResultsModelDataRaceCardPrizes>[];
      v.forEach((v) {
        arr0.add(RaceResultsModelDataRaceCardPrizes.fromJson(v));
      });
      prizes = arr0;
    }
    otherDeclarations = json["other_declarations"]?.toString();
    claimingPrices = json["claiming_prices"]?.toString();
    forfeits = json["forfeits"]?.toString();
    forfeitNumber = json["forfeit_number"]?.toString();
    forfeitValue = json["forfeit_value"]?.toString();
    stage = json["stage"]?.toString();
    highestOfficialRating = json["highest_official_rating"]?.toString();
    scoop6Race = json["scoop6_race"];
    lucky7Race = json["lucky7_race"];
    jackpotRace = json["jackpot_race"];
    williamHillOfferRace = json["william_hill_offer_race"];
    ladbrokesOfferRace = json["ladbrokes_offer_race"];
    safetyFactorNumber = json["safety_factor_number"]?.toInt();
    earlyClosingRace = json["early_closing_race"];
    reopened = json["reopened"];
    divisionPreference = json["division_preference"]?.toInt();
    lastYear = json["last_year"]?.toString();
    performRaceUidAtr = json["perform_race_uid_atr"]?.toInt();
    performRaceUidRuk = json["perform_race_uid_ruk"]?.toString();
    betToView = json["bet_to_view"];
    livestreamUid = json["livestream_uid"]?.toString();
    awSurfaceType = json["aw_surface_type"]?.toString();
    straightRoundJubileeCode = json["straight_round_jubilee_code"]?.toString();
    liveTab = json["live_tab"];
    claimingRace = json["claiming_race"];
    sellingRace = json["selling_race"];
    plus10Race = json["plus10_race"];
    weightForAge = json["weight_for_age"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["race_instance_title"] = raceInstanceTitle;
    data["race_number"] = raceNumber;
    data["rp_ages_allowed_desc"] = rpAgesAllowedDesc;
    data["race_class"] = raceClass;
    data["race_group_code"] = raceGroupCode;
    data["official_rating_band_desc"] = officialRatingBandDesc;
    data["race_datetime"] = raceDatetime;
    data["local_meeting_race_datetime"] = localMeetingRaceDatetime;
    data["three_yo_min_weight_lbs"] = threeYoMinWeightLbs;
    data["four_yo_min_weight_lbs"] = fourYoMinWeightLbs;
    data["minimum_weight_lbs"] = minimumWeightLbs;
    data["declared_runners"] = declaredRunners;
    data["no_of_runners"] = noOfRunners;
    data["distance_yard"] = distanceYard;
    data["distance_furlong_rounded"] = distanceFurlongRounded;
    data["rp_tv_text"] = rpTvText;
    data["going_type_desc"] = goingTypeDesc;
    data["rp_penalties"] = rpPenalties;
    data["course_uid"] = courseUid;
    data["mixed_course_uid"] = mixedCourseUid;
    data["course_name"] = courseName;
    data["course_style_name"] = courseStyleName;
    data["course_region"] = courseRegion;
    data["diffusion_course_name"] = diffusionCourseName;
    data["course_key"] = courseKey;
    data["small_map_image_path"] = smallMapImagePath;
    data["large_map_image_path"] = largeMapImagePath;
    data["rp_horse_types"] = rpHorseTypes;
    data["rp_weights"] = rpWeights;
    data["allowances"] = allowances;
    data["entry_fee"] = entryFee;
    data["extra_fee"] = extraFee;
    data["country_code"] = countryCode;
    data["foreign"] = foreign;
    data["rp_stakes"] = rpStakes;
    data["rp_ag_indicator"] = rpAgIndicator;
    data["weights_raised_lbs"] = weightsRaisedLbs;
    data["rp_auction_min"] = rpAuctionMin;
    data["rp_claim_min"] = rpClaimMin;
    data["rp_confirmed"] = rpConfirmed;
    data["race_status_code"] = raceStatusCode;
    data["race_type_code"] = raceTypeCode;
    data["race_group_desc"] = raceGroupDesc;
    data["going_type_code"] = goingTypeCode;
    data["no_of_fences"] = noOfFences;
    data["no_of_entries"] = noOfEntries;
    data["rp_stalls_position"] = rpStallsPosition;
    data["stalls_position_desc"] = stallsPositionDesc;
    if (prizes != null) {
      final v = prizes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["prizes"] = arr0;
    }
    data["other_declarations"] = otherDeclarations;
    data["claiming_prices"] = claimingPrices;
    data["forfeits"] = forfeits;
    data["forfeit_number"] = forfeitNumber;
    data["forfeit_value"] = forfeitValue;
    data["stage"] = stage;
    data["highest_official_rating"] = highestOfficialRating;
    data["scoop6_race"] = scoop6Race;
    data["lucky7_race"] = lucky7Race;
    data["jackpot_race"] = jackpotRace;
    data["william_hill_offer_race"] = williamHillOfferRace;
    data["ladbrokes_offer_race"] = ladbrokesOfferRace;
    data["safety_factor_number"] = safetyFactorNumber;
    data["early_closing_race"] = earlyClosingRace;
    data["reopened"] = reopened;
    data["division_preference"] = divisionPreference;
    data["last_year"] = lastYear;
    data["perform_race_uid_atr"] = performRaceUidAtr;
    data["perform_race_uid_ruk"] = performRaceUidRuk;
    data["bet_to_view"] = betToView;
    data["livestream_uid"] = livestreamUid;
    data["aw_surface_type"] = awSurfaceType;
    data["straight_round_jubilee_code"] = straightRoundJubileeCode;
    data["live_tab"] = liveTab;
    data["claiming_race"] = claimingRace;
    data["selling_race"] = sellingRace;
    data["plus10_race"] = plus10Race;
    data["weight_for_age"] = weightForAge;
    return data;
  }
}

class RaceResultsModelData {
/*
{
  "race_card": {
    "race_instance_title": "Hoof It For PRD British EBF Restricted Novice Stakes (For Horses In Bands A, B, C And D) (GBB Race)",
    "race_number": 1,
    "rp_ages_allowed_desc": "2yo",
    "race_class": "4",
    "race_group_code": null,
    "official_rating_band_desc": null,
    "race_datetime": "2021-09-03T13:20:00+01:00",
    "local_meeting_race_datetime": "2021-09-03T13:20:00+01:00",
    "three_yo_min_weight_lbs": null,
    "four_yo_min_weight_lbs": null,
    "minimum_weight_lbs": null,
    "declared_runners": 8,
    "no_of_runners": 8,
    "distance_yard": 1320,
    "distance_furlong_rounded": 6,
    "rp_tv_text": "SKY",
    "going_type_desc": "Good",
    "rp_penalties": "each race won 6lb (Sellers and Claimers excluded for the purposes of penalties)",
    "course_uid": 2,
    "mixed_course_uid": null,
    "course_name": "ASCOT",
    "course_style_name": "Ascot",
    "course_region": "GB & IRE",
    "diffusion_course_name": "ASCOT",
    "course_key": "ascot",
    "small_map_image_path": "//images.racingpost.com/course_maps/small/ascot.jpg",
    "large_map_image_path": "//images.racingpost.com/course_maps/large/ascot.jpg",
    "rp_horse_types": "2yo, which are EBF eligible, which are in Bands A, B, C, and D",
    "rp_weights": "colts & geldings 9st 5lb; fillies 9st",
    "allowances": "Band B from Band A 2lb; Band C from Band B 2lb; Band D from Band C 2lb (allowances are cumulative)",
    "entry_fee": 40,
    "extra_fee": null,
    "country_code": "GB",
    "foreign": 0,
    "rp_stakes": 10100,
    "rp_ag_indicator": "G",
    "weights_raised_lbs": null,
    "rp_auction_min": null,
    "rp_claim_min": null,
    "rp_confirmed": null,
    "race_status_code": "R",
    "race_type_code": "F",
    "race_group_desc": null,
    "going_type_code": "G",
    "no_of_fences": null,
    "no_of_entries": 20,
    "rp_stalls_position": "H",
    "stalls_position_desc": "Stands' side",
    "prizes": [
      {
        "position_no": 1,
        "prize_sterling": 5454,
        "prize_euro": null,
        "prize_usd": 7471.98
      }
    ],
    "other_declarations": null,
    "claiming_prices": null,
    "forfeits": null,
    "forfeit_number": null,
    "forfeit_value": null,
    "stage": null,
    "highest_official_rating": null,
    "scoop6_race": false,
    "lucky7_race": false,
    "jackpot_race": false,
    "william_hill_offer_race": false,
    "ladbrokes_offer_race": false,
    "safety_factor_number": 20,
    "early_closing_race": false,
    "reopened": false,
    "division_preference": 1,
    "last_year": "2020 (10 ran) Dark Shift (5) Charles Hills 2 9-2 10/1 Kieran Shoemark RPR94",
    "perform_race_uid_atr": 846046,
    "perform_race_uid_ruk": null,
    "bet_to_view": false,
    "livestream_uid": null,
    "aw_surface_type": null,
    "straight_round_jubilee_code": null,
    "live_tab": false,
    "claiming_race": false,
    "selling_race": false,
    "plus10_race": false,
    "weight_for_age": null
  }
} 
*/

  RaceResultsModelDataRaceCard? raceCard;

  RaceResultsModelData({
    this.raceCard,
  });
  RaceResultsModelData.fromJson(Map<String, dynamic> json) {
    raceCard = (json["race_card"] != null)
        ? RaceResultsModelDataRaceCard.fromJson(json["race_card"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (raceCard != null) {
      data["race_card"] = raceCard!.toJson();
    }
    return data;
  }
}

class RaceResultsModel {
/*
{
  "data": {
    "race_card": {
      "race_instance_title": "Hoof It For PRD British EBF Restricted Novice Stakes (For Horses In Bands A, B, C And D) (GBB Race)",
      "race_number": 1,
      "rp_ages_allowed_desc": "2yo",
      "race_class": "4",
      "race_group_code": null,
      "official_rating_band_desc": null,
      "race_datetime": "2021-09-03T13:20:00+01:00",
      "local_meeting_race_datetime": "2021-09-03T13:20:00+01:00",
      "three_yo_min_weight_lbs": null,
      "four_yo_min_weight_lbs": null,
      "minimum_weight_lbs": null,
      "declared_runners": 8,
      "no_of_runners": 8,
      "distance_yard": 1320,
      "distance_furlong_rounded": 6,
      "rp_tv_text": "SKY",
      "going_type_desc": "Good",
      "rp_penalties": "each race won 6lb (Sellers and Claimers excluded for the purposes of penalties)",
      "course_uid": 2,
      "mixed_course_uid": null,
      "course_name": "ASCOT",
      "course_style_name": "Ascot",
      "course_region": "GB & IRE",
      "diffusion_course_name": "ASCOT",
      "course_key": "ascot",
      "small_map_image_path": "//images.racingpost.com/course_maps/small/ascot.jpg",
      "large_map_image_path": "//images.racingpost.com/course_maps/large/ascot.jpg",
      "rp_horse_types": "2yo, which are EBF eligible, which are in Bands A, B, C, and D",
      "rp_weights": "colts & geldings 9st 5lb; fillies 9st",
      "allowances": "Band B from Band A 2lb; Band C from Band B 2lb; Band D from Band C 2lb (allowances are cumulative)",
      "entry_fee": 40,
      "extra_fee": null,
      "country_code": "GB",
      "foreign": 0,
      "rp_stakes": 10100,
      "rp_ag_indicator": "G",
      "weights_raised_lbs": null,
      "rp_auction_min": null,
      "rp_claim_min": null,
      "rp_confirmed": null,
      "race_status_code": "R",
      "race_type_code": "F",
      "race_group_desc": null,
      "going_type_code": "G",
      "no_of_fences": null,
      "no_of_entries": 20,
      "rp_stalls_position": "H",
      "stalls_position_desc": "Stands' side",
      "prizes": [
        {
          "position_no": 1,
          "prize_sterling": 5454,
          "prize_euro": null,
          "prize_usd": 7471.98
        }
      ],
      "other_declarations": null,
      "claiming_prices": null,
      "forfeits": null,
      "forfeit_number": null,
      "forfeit_value": null,
      "stage": null,
      "highest_official_rating": null,
      "scoop6_race": false,
      "lucky7_race": false,
      "jackpot_race": false,
      "william_hill_offer_race": false,
      "ladbrokes_offer_race": false,
      "safety_factor_number": 20,
      "early_closing_race": false,
      "reopened": false,
      "division_preference": 1,
      "last_year": "2020 (10 ran) Dark Shift (5) Charles Hills 2 9-2 10/1 Kieran Shoemark RPR94",
      "perform_race_uid_atr": 846046,
      "perform_race_uid_ruk": null,
      "bet_to_view": false,
      "livestream_uid": null,
      "aw_surface_type": null,
      "straight_round_jubilee_code": null,
      "live_tab": false,
      "claiming_race": false,
      "selling_race": false,
      "plus10_race": false,
      "weight_for_age": null
    }
  },
  "status": 200
} 
*/

  RaceResultsModelData? data;
  int? status;

  RaceResultsModel({
    this.data,
    this.status,
  });
  RaceResultsModel.fromJson(Map<String, dynamic> json) {
    data = (json["data"] != null)
        ? RaceResultsModelData.fromJson(json["data"])
        : null;
    status = json["status"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status"] = status;
    return data;
  }
}

class RaceResultsProvider extends ChangeNotifier {
  RaceResultsModel? raceData;
  RaceRunnersModel? runners;
  addRaceDetails(RaceResultsModel data) {
    raceData = data;
    notifyListeners();
  }

  addRaceRunners(RaceRunnersModel data) {
    runners = data;
    notifyListeners();
  }
}
