///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VideosModel {
/*
{
  "embed": "https://www.youtube.com/embed/wnkBaoy6OmQ",
  "link": "https://www.youtube.com/watch?v=wnkBaoy6OmQ",
  "title": "test",
  "description": "sample",
  "created_at": "2022-05-15 00:23:06"
} 
*/

  String? embed;
  String? link;
  String? title;
  String? description;
  String? createdAt;

  VideosModel({
    this.embed,
    this.link,
    this.title,
    this.description,
    this.createdAt,
  });
  VideosModel.fromJson(Map<String, dynamic> json) {
    embed = json['embed']?.toString();
    link = json['link']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    createdAt = json['created_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['embed'] = embed;
    data['link'] = link;
    data['title'] = title;
    data['description'] = description;
    data['created_at'] = createdAt;
    return data;
  }
}
