///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OwnerEntries {
/*
{
  "id": 157,
  "owner_uid": 302438,
  "horse_uid": "3201895",
  "horse_name": "Mejthaam",
  "race_datetime": "2021-10-21 19:30:00",
  "course_uid": "513",
  "course_name": "WOLVERHAMPTON (A.W)",
  "course_style_name": "Wolverhampton (AW)",
  "created_at": "2021-10-16 10:23:45",
  "updated_at": "2021-10-16 10:23:45",
  "race_instance_uid": "793815"
}
*/

  int? id;
  int? index;
  int? ownerUid;
  String? horseUid;
  String? horseName;
  String? raceDatetime;
  String? courseUid;
  String? courseName;
  String? courseStyleName;
  String? createdAt;
  String? updatedAt;
  String? raceInstanceUid;
  String? raceInstanceTitle;

  OwnerEntries(
      {this.id,
      this.ownerUid,
      this.horseUid,
      this.horseName,
      this.raceDatetime,
      this.courseUid,
      this.courseName,
      this.courseStyleName,
      this.createdAt,
      this.updatedAt,
      this.raceInstanceUid,
      this.raceInstanceTitle});
  OwnerEntries.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    ownerUid = json["owner_uid"]?.toInt();
    horseUid = json["horse_uid"]?.toString();
    horseName = json["horse_name"]?.toString();
    raceDatetime = json["race_datetime"]?.toString();
    courseUid = json["course_uid"]?.toString();
    courseName = json["course_name"]?.toString();
    courseStyleName = json["course_style_name"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    raceInstanceUid = json["race_instance_uid"]?.toString();
    raceInstanceTitle = json["race_instance_title"].toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["owner_uid"] = ownerUid;
    data["horse_uid"] = horseUid;
    data["horse_name"] = horseName;
    data["race_datetime"] = raceDatetime;
    data["course_uid"] = courseUid;
    data["course_name"] = courseName;
    data["course_style_name"] = courseStyleName;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["race_instance_uid"] = raceInstanceUid;
    return data;
  }
}
