///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StatsSummary {
  String? year;
  String? wins;
  String? runs;
  String? percentWinsRuns;
  String? earnings;
  String? stake;

  StatsSummary({
    this.year,
    this.wins,
    this.runs,
    this.percentWinsRuns,
    this.earnings,
    this.stake,
  });
  StatsSummary.fromJson(Map<String, dynamic> json) {
    year = json["year"]?.toString();
    wins = json["wins"]?.toString();
    runs = json["runs"]?.toString();
    percentWinsRuns = json["percent_wins_runs"]?.toString();
    earnings = json["earnings"]?.toString();
    stake = json["stake"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["year"] = year;
    data["wins"] = wins;
    data["runs"] = runs;
    data["percent_wins_runs"] = percentWinsRuns;
    data["earnings"] = earnings;
    data["stake"] = stake;
    return data;
  }
}
